language: go
go: 1.6
sudo: false
before_install:
  - wget http://apache.claz.org/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
  - tar -zxvf zookeeper*tar.gz
before_script:
  - make
  - export NN_PORT=9000
  - export HADOOP_NAMENODE="localhost:$NN_PORT"
  - export HADOOP_DISTRO=cdh
  - export HADOOP_HOME="$HOME/hadoop"
  - sh vendor/github.com/colinmarc/hdfs/setup_test_env.sh
script: make test
before_deploy: make release
deploy:
  provider: releases
  api_key:
    secure: mA5a0ALLaHxlfSDfqOmr+7fpcUv5/nThZVTyFTiXGRRvfUCUMdJzmQp5d74fLfa5ExQz8cXqswIYQT0ScBEBIiu48p8v4qLLYGonorNVam51m93/m9k9PAHZFIaaqW3QJAr9kZdS+Z+epf3U7dcpRfHWwkeLxHW+X2EErJpNAtw=
  file: sequins-*.tar.gz
  file_glob: true
  on:
    repo: stripe/sequins
    tags: true
    all_branches: true
cache:
  - $HADOOP_HOME
