os:
  - linux
  - osx
language: go
go: 1.7
sudo: false
before_install:
- export ZOOKEEPER_HOME="$HOME/zookeeper-3.4.8"
- test -d $ZOOKEEPER_HOME || (cd $HOME && wget http://apache.mirror.iphh.net/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz
  && tar -zxvf zookeeper-3.4.8.tar.gz)
- export NN_PORT=9000
- export HADOOP_NAMENODE="localhost:$NN_PORT"
- export HADOOP_DISTRO=cdh
- export HADOOP_HOME="$HOME/hadoop"
- sh vendor/github.com/colinmarc/hdfs/setup_test_env.sh
before_script:
- make
script: make test
before_deploy: make release
cache:
  directories:
  - "$ZOOKEEPER_HOME"
  - "$HADOOP_HOME"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bNI1zixTuod6PBhCQzeGvZYOODqlEq0iRepcV5M6avVRbYMhW5zX4zxCfP155LXB9rA+xPpP0DEMVTAw9Q0MMSvdKPaBjQNlMPn87vZw6N09UajPYX8YZoUvxZD5XMBVFLsswC4oDaCptD/g6ilMQBT8hySHO8SFYjNWAGq04xM=
  file: sequins-*.tar.gz
  file_glob: true
  on:
    repo: stripe/sequins
    tags: true
    all_branches: true
env:
  global:
  - secure: INFoLu2JnDmONLHbG6RrM19AZby1UDtC1XzJ4QzA0CiDhsd0bFKKDgYF+GVIi3ibLfwEnkk8sPA7q+Mj6/b8hlIy2gyHmCSVDMOkUlWZU37RehpIFAQU/PlIhYi6yYRCXJKsGRuxe+vE/F1kM/zdEzBvecmSPMAsZNxaW1jULUI=
  - secure: AvFzMf2bVwpU2KYH811CeD419pX9h3fc/gc/C8fvQ5tzRE1mEFJuFALnDx3WvI4WO9RctEt/Pr71RbecdBVMmYZOuFF9PvEFRegGpOj1+uIbdbe7PAtr3gsmlHYxlXFCQ5KTYPYTy4YK5DfRGaK1ZKSBgmYQc1ZLWFJHOYY7324=
  - secure: Cg7Tg8kTVHhAZmHI+sAIuQNP6vHp5RU/U+M8INN13b+5DrIA56bxYoYkOgSAexv6v2gWPmjPmFxopfKMWbgdsRQ0OOmCqMOceAUTLHSodPOvg7lW156/fBNIE9X+pKqCaQphAYztbvQyhVuqsXKyMGOKo2eBbGZ0YQgXDBCSLos=
