language: go
go: 1.6
sudo: false
before_install:
- export ZOOKEEPER_HOME="$HOME/zookeeper-3.4.8"
- test -d $ZOOKEEPER_HOME || (cd $HOME &&
    wget http://apache.mirror.iphh.net/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz &&
    tar -zxvf zookeeper-3.4.8.tar.gz)
- export NN_PORT=9000
- export HADOOP_NAMENODE="localhost:$NN_PORT"
- export HADOOP_DISTRO=cdh
- export HADOOP_HOME="$HOME/hadoop"
- sh vendor/github.com/colinmarc/hdfs/setup_test_env.sh
before_script:
- make
script: make test
before_deploy: make release
cache:
  directories:
  - "$ZOOKEEPER_HOME"
  - "$HADOOP_HOME"
deploy:
  provider: releases
  api_key:
    secure: bNI1zixTuod6PBhCQzeGvZYOODqlEq0iRepcV5M6avVRbYMhW5zX4zxCfP155LXB9rA+xPpP0DEMVTAw9Q0MMSvdKPaBjQNlMPn87vZw6N09UajPYX8YZoUvxZD5XMBVFLsswC4oDaCptD/g6ilMQBT8hySHO8SFYjNWAGq04xM=
  file: sequins-*.tar.gz
  file_glob: true
  on:
    repo: stripe/sequins
    tags: true
    all_branches: true
env:
  global:
  - secure: d4y27NWdKd13Nj0y9aBJBiJaQLSCw+FHI5W2UXaXPkgi7NCr/dsNYhFfkNSNDR7NVLjeNoG0Ga/488DNeetm/InXvb4iST+sjpBgHhFot97ytqCkQ64bU7QoGG0cu4bI4mgMVPwkVE71NY0bx3mzj+CTZgK/PtBvpB0f8rrXZbc=
  - secure: wz8uS6uPznAOojsOX7a7RCaae/KDV9r/2N2lLVWxUdLZ6OZ2ZL2Sh8e6aN73JrWc3h/C2/Km7DZysKmVXtnbdZqkZbEP3KjWu9e2t3rC7DZaJxG/8Xr/2PqwU1NBfEzhSS8AMsI8BCNHFcFsYWwJek/+JWXk5+MWhNTwbd3EMcc=
  - secure: lngtapRncQZGX5D5X5B7TheLjrTW5gmdPwBSD3z/z7R/q7Q8JaWITXk2N4eRkSvrU6J9n/vm9VIFIq95Pm/MraM4X73q72EMXAH55TmVUzWXTjLVPVRnkH4FwB4QFbir/JYD5nNzWZZ6dzl4mv07AsSA8OoExubDfF1Y8/MPdoA=
  - secure: jkhnGrRC14xbeEYL2twJaTBHaPCxewl97rgs+yS83KtvMXyODtpL6GRsfJNW01+by+gqcY/MeW0z8BjU4D1ul0Jf/Wa/I5YIfvaVQf/eZuSb43akAfr5I53pnC+HyRwcIsDmnQXbCfDWXo7+SVDeM5ZGq8H1HOV6ENfh6+020IY=
